site_name: ToolDiy
site_url: https://github.com/cargo-youth/ToolDiy/

repo_name: ToolDiy
repo_url: https://github.com/cargo-youth/ToolDiy

edit_uri: blob/main/docs/

# 主题设置
theme:
  name: material
  language: zh
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 亮色模式
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=nav#navigation-tabs
    - navigation.tabs
    - navigation.tabs.sticky
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=edit#code-actions
    - content.action.edit


# 导航
# 目前导航已经采用自动生成的方式，所以你只需要在下面的插件
# 部分的 nav_translations 填写对应的翻译即可，请不要在这
# 里进行添加操作
nav:
  - 简介 :
    - 前言 : "index.md"
    - 规范 :
      - PR规范 : "specification/pr.md"
      - Markdown规范 :
        - 基础语法 : "specification/markdown/markdown.md"
        - LaTex语法 : "specification/markdown/latex.md"
        - 中英混排 : "specification/markdown/chinese_copywriting_guidelines.md"
    - 写作模板 : "specification/template.md"
  - ...

# 版权
copyright: This website follows CC BY-SA 4.0

# 插件
plugins:
  - i18n:
      default_language: zh
      material_alternate: true
      languages:
        zh:
          name: 简体中文
          build: true
        en:
          name: English
          build: true
      nav_translations:
        zh:
          How to Contribute : 如何贡献
          One click deployment : 一键部署
          Platform : 平台
          Plugins : 插件
          Software : 软件
        en:
          简介 : Introduction
          前言 : Preface
          规范 : Specification
          PR规范 : PR Specification
          Markdown规范 : Markdown Specification
          基础语法 : Markdown Syntax
          LaTex语法 : LaTeX Syntax
          中英混排 : Chinese With English
          写作模板 : Writing Template
          软件 : Software
          插件 : Plugins
          平台 : Platform
          一键部署: One-Click Deployment
  - search:
      lang: ja
  - awesome-pages

# LaTeX支持
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
